In [21]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer=CountVectorizer()

corpus=[
    'THis is Mentoring',
    'Morning is Training',
    'Mentoring is to Practice'
]

vectorized=vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
sparse_matrix=vectorized.toarray()
print(sparse_matrix)
print(vectorizer.vocabulary_)

new_doc = ['This is Practice']

print(vectorizer.transform(new_doc).toarray())  # Transform new data using the same vocabulary.



['is' 'mentoring' 'morning' 'practice' 'this' 'to' 'training']
[[1 1 0 0 1 0 0]
 [1 0 1 0 0 0 1]
 [1 1 0 1 0 1 0]]
{'this': 4, 'is': 0, 'mentoring': 1, 'morning': 2, 'training': 6, 'to': 5, 'practice': 3}
[[1 0 0 1 1 0 0]]


In [28]:
corpus = [
    "Python is easy to learn",
    "Python is used for data science",
    "Machine learning uses Python",
    "Data science is fun and exciting",
    "Deep learning is a part of artificial intelligence",
    "Artificial intelligence is changing the world",
    "Python and machine learning go together",
    "Data analysis is important in data science",
    "Learning Python improves programming skills",
    "Artificial intelligence and machine learning are popular"
]

vectorizer=CountVectorizer(min_df=2,max_df=0.75,ngram_range=(1,2),stop_words='english',max_features=10,binary=True)
vectorized=vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print(vectorized.toarray())

new_doc=['NLP is for text data']
print(vectorizer.transform(new_doc).toarray())

print(vectorizer.vocabulary_)


['artificial' 'artificial intelligence' 'data' 'data science'
 'intelligence' 'learning' 'machine' 'machine learning' 'python' 'science']
[[0 0 0 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 0 0 1 1]
 [0 0 0 0 0 1 1 1 1 0]
 [0 0 1 1 0 0 0 0 0 1]
 [1 1 0 0 1 1 0 0 0 0]
 [1 1 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 0]
 [0 0 1 1 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 1 0]
 [1 1 0 0 1 1 1 1 0 0]]
[[0 0 1 0 0 0 0 0 0 0]]
{'python': np.int64(8), 'data': np.int64(2), 'science': np.int64(9), 'data science': np.int64(3), 'machine': np.int64(6), 'learning': np.int64(5), 'machine learning': np.int64(7), 'artificial': np.int64(0), 'intelligence': np.int64(4), 'artificial intelligence': np.int64(1)}
