In [ ]:
import pandas as pd


In [ ]:
text="""Hello Everyone! 👋

I'm Venu, and I absolutely LOVE learning Data Science, Machine Learning, and NLP. 😍
Recently, I completed 5 amazing projects in Python using Scikit-learn, Pandas, and NumPy.

You can visit my portfolio at https://www.myportfolio.com or check GitHub: https://github.com/VenuMadhav-IN18.

<p>I can't wait to become a Data Scientist by December 2026!</p>

The price of one laptop was $799.99, but now it's only $699 after a 15% discount!!

Wow!!! Isn't that amazing? 😊

Email me at venu@example.com or call +91-9876543210.

Artificial Intelligence (AI) and Natural Language Processing (NLP) are changing the world every single day!!!"""

In [ ]:
# lower case
text=text.lower()

In [ ]:
from bs4 import BeautifulSoup

text=BeautifulSoup(text,'html.parser').get_text()

In [ ]:
pip install Contractions

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.1/345.1 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 8.7 MB/s eta 0:00:00


In [ ]:
# Expand Contractions
import contractions
text=contractions.fix(text)
text

'hello everyone! 👋\n\ni am venu, and i absolutely love learning data science, machine learning, and nlp. 😍\nrecently, i completed 5 amazing projects in python using scikit-learn, pandas, and numpy.\n\nyou can visit my portfolio at https://www.myportfolio.com or check github: https://github.com/venumadhav-in18.\n\ni cannot wait to become a data scientist by december 2026!\n\nthe price of one laptop was $799.99, but now it is only $699 after a 15% discount!!\n\nwow!!! is not that amazing? 😊\n\nemail me at venu@example.com or call +91-9876543210.\n\nartificial intelligence (ai) and natural language processing (nlp) are changing the world every single day!!!'

In [ ]:
# remove punchuations
import string
cleaned=text.translate(str.maketrans("","",string.punctuation))
print(cleaned)

hello everyone 👋

i am venu and i absolutely love learning data science machine learning and nlp 😍
recently i completed 5 amazing projects in python using scikitlearn pandas and numpy

you can visit my portfolio at httpswwwmyportfoliocom or check github httpsgithubcomvenumadhavin18

i cannot wait to become a data scientist by december 2026

the price of one laptop was 79999 but now it is only 699 after a 15 discount

wow is not that amazing 😊

email me at venuexamplecom or call 919876543210

artificial intelligence ai and natural language processing nlp are changing the world every single day


In [ ]:
# removing extra spaces
text=" ".join(cleaned.split())

In [ ]:
# removing URLS
import re
text=re.sub(r'https\S+','',text)

In [ ]:
# removing email
text=re.sub(r'\S+com\W','',text)
text

'hello everyone 👋 i am venu and i absolutely love learning data science machine learning and nlp 😍 recently i completed 5 amazing projects in python using scikitlearn pandas and numpy you can visit my portfolio at  or check github  i cannot wait to become a data scientist by december 2026 the price of one laptop was 79999 but now it is only 699 after a 15 discount wow is not that amazing 😊 email me at or call 919876543210 artificial intelligence ai and natural language processing nlp are changing the world every single day'

In [ ]:
pip install emoji

In [ ]:
# removing Emojis
import emoji
text=emoji.replace_emoji(text,"")

In [ ]:
text

'hello everyone  i am venu and i absolutely love learning data science machine learning and nlp  recently i completed 5 amazing projects in python using scikitlearn pandas and numpy you can visit my portfolio at  or check github  i cannot wait to become a data scientist by december 2026 the price of one laptop was 79999 but now it is only 699 after a 15 discount wow is not that amazing  email me at or call 919876543210 artificial intelligence ai and natural language processing nlp are changing the world every single day'

In [ ]:
 # removing phone number
 text=re.sub(r'91\S+',"",text)
 text

'hello everyone  i am venu and i absolutely love learning data science machine learning and nlp  recently i completed 5 amazing projects in python using scikitlearn pandas and numpy you can visit my portfolio at  or check github  i cannot wait to become a data scientist by december 2026 the price of one laptop was 79999 but now it is only 699 after a 15 discount wow is not that amazing  email me at or call  artificial intelligence ai and natural language processing nlp are changing the world every single day'

In [ ]:
# removing numbers
text=re.sub(r'\d',"",text)
print(text)

hello everyone  i am venu and i absolutely love learning data science machine learning and nlp  recently i completed  amazing projects in python using scikitlearn pandas and numpy you can visit my portfolio at  or check github  i cannot wait to become a data scientist by december  the price of one laptop was  but now it is only  after a  discount wow is not that amazing  email me at or call  artificial intelligence ai and natural language processing nlp are changing the world every single day


In [ ]:
cleaned_text=" ".join(text.split())

In [ ]:
cleaned_text

'hello everyone i am venu and i absolutely love learning data science machine learning and nlp recently i completed amazing projects in python using scikitlearn pandas and numpy you can visit my portfolio at or check github i cannot wait to become a data scientist by december the price of one laptop was but now it is only after a discount wow is not that amazing email me at or call artificial intelligence ai and natural language processing nlp are changing the world every single day'

## Tokenization

In [ ]:
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import sent_tokenize

sent_tokenize(cleaned_text)


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


['hello everyone i am venu and i absolutely love learning data science machine learning and nlp recently i completed amazing projects in python using scikitlearn pandas and numpy you can visit my portfolio at or check github i cannot wait to become a data scientist by december the price of one laptop was but now it is only after a discount wow is not that amazing email me at or call artificial intelligence ai and natural language processing nlp are changing the world every single day']

In [ ]:
from nltk.tokenize import word_tokenize
word_tokens=word_tokenize(cleaned_text)
word_tokens

['hello',
 'everyone',
 'i',
 'am',
 'venu',
 'and',
 'i',
 'absolutely',
 'love',
 'learning',
 'data',
 'science',
 'machine',
 'learning',
 'and',
 'nlp',
 'recently',
 'i',
 'completed',
 'amazing',
 'projects',
 'in',
 'python',
 'using',
 'scikitlearn',
 'pandas',
 'and',
 'numpy',
 'you',
 'can',
 'visit',
 'my',
 'portfolio',
 'at',
 'or',
 'check',
 'github',
 'i',
 'can',
 'not',
 'wait',
 'to',
 'become',
 'a',
 'data',
 'scientist',
 'by',
 'december',
 'the',
 'price',
 'of',
 'one',
 'laptop',
 'was',
 'but',
 'now',
 'it',
 'is',
 'only',
 'after',
 'a',
 'discount',
 'wow',
 'is',
 'not',
 'that',
 'amazing',
 'email',
 'me',
 'at',
 'or',
 'call',
 'artificial',
 'intelligence',
 'ai',
 'and',
 'natural',
 'language',
 'processing',
 'nlp',
 'are',
 'changing',
 'the',
 'world',
 'every',
 'single',
 'day']

## Stopwors Removal

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

In [87]:
stop_words=stopwords.words('english')
filtered=[word for word in word_tokens if word not in stop_words]
print(filtered)

['hello', 'everyone', 'venu', 'absolutely', 'love', 'learning', 'data', 'science', 'machine', 'learning', 'nlp', 'recently', 'completed', 'amazing', 'projects', 'python', 'using', 'scikitlearn', 'pandas', 'numpy', 'visit', 'portfolio', 'check', 'github', 'wait', 'become', 'data', 'scientist', 'december', 'price', 'one', 'laptop', 'discount', 'wow', 'amazing', 'email', 'call', 'artificial', 'intelligence', 'ai', 'natural', 'language', 'processing', 'nlp', 'changing', 'world', 'every', 'single', 'day']


## stemming

In [88]:
from nltk.stem import PorterStemmer
stemmer=PorterStemmer()
for word in filtered:
  print(word,"->",stemmer.stem(word))

hello -> hello
everyone -> everyon
venu -> venu
absolutely -> absolut
love -> love
learning -> learn
data -> data
science -> scienc
machine -> machin
learning -> learn
nlp -> nlp
recently -> recent
completed -> complet
amazing -> amaz
projects -> project
python -> python
using -> use
scikitlearn -> scikitlearn
pandas -> panda
numpy -> numpi
visit -> visit
portfolio -> portfolio
check -> check
github -> github
wait -> wait
become -> becom
data -> data
scientist -> scientist
december -> decemb
price -> price
one -> one
laptop -> laptop
discount -> discount
wow -> wow
amazing -> amaz
email -> email
call -> call
artificial -> artifici
intelligence -> intellig
ai -> ai
natural -> natur
language -> languag
processing -> process
nlp -> nlp
changing -> chang
world -> world
every -> everi
single -> singl
day -> day


In [89]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [100]:
from nltk.stem import WordNetLemmatizer

lemmatizer=WordNetLemmatizer()

tokens=[]
words=[]
for word in filtered:
  tokens.append(lemmatizer.lemmatize(word,pos='v'))
for word in tokens:
  words.append(lemmatizer.lemmatize(word,pos='a'))
words

['hello',
 'everyone',
 'venu',
 'absolutely',
 'love',
 'learn',
 'data',
 'science',
 'machine',
 'learn',
 'nlp',
 'recently',
 'complete',
 'amaze',
 'project',
 'python',
 'use',
 'scikitlearn',
 'pandas',
 'numpy',
 'visit',
 'portfolio',
 'check',
 'github',
 'wait',
 'become',
 'data',
 'scientist',
 'december',
 'price',
 'one',
 'laptop',
 'discount',
 'wow',
 'amaze',
 'email',
 'call',
 'artificial',
 'intelligence',
 'ai',
 'natural',
 'language',
 'process',
 'nlp',
 'change',
 'world',
 'every',
 'single',
 'day']

## Vectorization

### OneHotEncoding


In [105]:
import numpy as np
words = np.array(words).reshape(-1, 1)
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()
encoded=encoder.fit_transform(words)
encoded.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [108]:
from sklearn.feature_extraction.text import CountVectorizer
words = words.ravel()
vectorizer=CountVectorizer()
vectorized=vectorizer.fit_transform(words)
print(vectorizer.get_feature_names_out())
sparse_matrix=vectorized.toarray()
print(sparse_matrix)
print(vectorizer.vocabulary_)

['absolutely' 'ai' 'amaze' 'artificial' 'become' 'call' 'change' 'check'
 'complete' 'data' 'day' 'december' 'discount' 'email' 'every' 'everyone'
 'github' 'hello' 'intelligence' 'language' 'laptop' 'learn' 'love'
 'machine' 'natural' 'nlp' 'numpy' 'one' 'pandas' 'portfolio' 'price'
 'process' 'project' 'python' 'recently' 'science' 'scientist'
 'scikitlearn' 'single' 'use' 'venu' 'visit' 'wait' 'world' 'wow']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
{'hello': 17, 'everyone': 15, 'venu': 40, 'absolutely': 0, 'love': 22, 'learn': 21, 'data': 9, 'science': 35, 'machine': 23, 'nlp': 25, 'recently': 34, 'complete': 8, 'amaze': 2, 'project': 32, 'python': 33, 'use': 39, 'scikitlearn': 37, 'pandas': 28, 'numpy': 26, 'visit': 41, 'portfolio': 29, 'check': 7, 'github': 16, 'wait': 42, 'become': 4, 'scientist': 36, 'december': 11, 'price': 30, 'one': 27, 'laptop': 20, 'discount': 12, 'wow': 44, 'email': 13, 'call': 

In [109]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

tfidf = vectorizer.fit_transform(words)

print(vectorizer.get_feature_names_out())

print(tfidf.toarray())

['absolutely' 'ai' 'amaze' 'artificial' 'become' 'call' 'change' 'check'
 'complete' 'data' 'day' 'december' 'discount' 'email' 'every' 'everyone'
 'github' 'hello' 'intelligence' 'language' 'laptop' 'learn' 'love'
 'machine' 'natural' 'nlp' 'numpy' 'one' 'pandas' 'portfolio' 'price'
 'process' 'project' 'python' 'recently' 'science' 'scientist'
 'scikitlearn' 'single' 'use' 'venu' 'visit' 'wait' 'world' 'wow']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
